name: Build menu image from PDF

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5'  # Weekdays at 05:00 UTC

concurrency:
  group: pdf_to_png
  cancel-in-progress: true

jobs:
  pdf_to_png:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout (full history so we can rebase)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils imagemagick curl

      - name: Fetch PDF
        run: |
          mkdir -p docs
          curl -L -o docs/menu.pdf \
            "https://qnips.blob.core.windows.net/release-menu-pdfs-static/SPEISEPLAN_Schachermayer-Menueplan_de.pdf"
          ls -lah docs

      - name: Convert first page to PNG (no trim, fit to 1920x1080)
        run: |
          pdftoppm -f 1 -l 1 -png -rx 300 -ry 300 docs/menu.pdf docs/menu_raw
          if [ ! -f docs/menu_raw-1.png ]; then
            echo "ERROR: docs/menu_raw-1.png not found; conversion failed." >&2
            exit 1
          fi
          # Keep the full page and resize/canvas it for a 1920x1080 TV screen
          convert docs/menu_raw-1.png \
            -background white -alpha remove -alpha off \
            -resize 1920x1080 \
            -gravity center -extent 1920x1080 \
            docs/menu.png
          ls -lah docs

      - name: Upload PNG as artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: menu-png
          path: docs/menu.png

      - name: Pull/rebase and push PNG if changed
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A docs/menu.png
          if git diff --cached --quiet; then
            echo "No changes to docs/menu.png"
            exit 0
          fi

          git fetch origin "$BRANCH_NAME"
          git pull --rebase origin "$BRANCH_NAME" || true

          git commit -m "chore: update menu.png from latest PDF [skip ci]" || true
          git push origin HEAD:"$BRANCH_NAME"
